language: go
go:
  - "1.x"
  - "1.11.x"
  - master
env:
  global:
    - GO111MODULE=on
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - # Do not install yet, since we want it to happen inside the script step below.
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)  # Make sure formatting is correct.
  - go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
  - go tool vet .
  - go test -v -race ./...
